version: '3.1'

services:
  bert_pretraining:
    image: bert_pretraining:1.1
    restart: always
    volumes:
      - /home/p0l3/RAD/BERT_PRETRAINING/PRETRAINING/:/PRETRAINING
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        resources:
          limits:
            memory: 64g
            cpus: '16'
    

